server:
  port: 7000

spring:
  application:
    name: rocketmq

#cloud:
#  consul:
#    host: localhost
#    port: 8500
#    discovery:
#      service-name: ${spring.application.name}
#
#feign:
#  hystrix:
#    enabled: true